In [3]:

import numpy as np

In [4]:

array_1d = np.linspace(0, 1, 20)
identity_matrix = np.eye(5)
random_matrix = np.random.randint(1, 101, size=(3, 4))
print("Array 1 (1-D evenly spaced):")
print(f"  Shape: {array_1d.shape}")
print(f"  Data Type: {array_1d.dtype}")
print(f"  Values: {array_1d}\n")

print("Array 2 (5×5 identity matrix):")
print(f"  Shape: {identity_matrix.shape}")
print(f"  Data Type: {identity_matrix.dtype}")
print(f"  Values:\n{identity_matrix}\n")

print("Array 3 (3×4 random integers):")
print(f"  Shape: {random_matrix.shape}")
print(f"  Data Type: {random_matrix.dtype}")
print(f"  Values:\n{random_matrix}")

Array 1 (1-D evenly spaced):
  Shape: (20,)
  Data Type: float64
  Values: [0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]

Array 2 (5×5 identity matrix):
  Shape: (5, 5)
  Data Type: float64
  Values:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Array 3 (3×4 random integers):
  Shape: (3, 4)
  Data Type: int32
  Values:
[[25 32 63 10]
 [79 58 16 75]
 [29 36 69 69]]


In [5]:
import numpy as np

# Create a 1-D array of integers from 1 to 24
arr_1d = np.arange(1, 25)
print("Original 1-D array:")
print(arr_1d)
print(f"Shape: {arr_1d.shape}\n")
print("=" * 70)

# Reshape to (2, 3, 4)
print("\n### Reshape to (2, 3, 4) ###")
arr_2_3_4 = arr_1d.reshape(2, 3, 4)
print(arr_2_3_4)
print(f"Shape: {arr_2_3_4.shape}")
print("\nML Scenario Interpretation:")
print("  - Dimension 0 (size 2): 2 batches of data")
print("  - Dimension 1 (size 3): 3 timesteps (e.g., sequence length in RNN/LSTM)")
print("  - Dimension 2 (size 4): 4 features per timestep")
print("  Example: 2 sequences, each with 3 time steps, 4 features each")
print("=" * 70)

# Reshape to (6, 4)
print("\n### Reshape to (6, 4) ###")
arr_6_4 = arr_2_3_4.reshape(6, 4)
print(arr_6_4)
print(f"Shape: {arr_6_4.shape}")
print("\nML Scenario Interpretation:")
print("  - Dimension 0 (size 6): 6 samples")
print("  - Dimension 1 (size 4): 4 features")
print("  Example: 6 data points with 4 features each (typical tabular data)")
print("=" * 70)

# Flatten back to 1-D
print("\n### Flatten back to 1-D ###")
arr_1d_final = arr_6_4.flatten()
print(arr_1d_final)
print(f"Shape: {arr_1d_final.shape}")
print("\nML Scenario Interpretation:")
print("  - Single 1-D array: Can be used as input to fully connected layers")
print("  - Or serialized for storage/transmission")
print("=" * 70)


print("\n### Verification ###")
print(f"Original and final arrays are equal: {np.array_equal(arr_1d, arr_1d_final)}")
print(f"Total elements preserved: {arr_1d.size} -> {arr_1d_final.size}")

Original 1-D array:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
Shape: (24,)


### Reshape to (2, 3, 4) ###
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
Shape: (2, 3, 4)

ML Scenario Interpretation:
  - Dimension 0 (size 2): 2 batches of data
  - Dimension 1 (size 3): 3 timesteps (e.g., sequence length in RNN/LSTM)
  - Dimension 2 (size 4): 4 features per timestep
  Example: 2 sequences, each with 3 time steps, 4 features each

### Reshape to (6, 4) ###
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
Shape: (6, 4)

ML Scenario Interpretation:
  - Dimension 0 (size 6): 6 samples
  - Dimension 1 (size 4): 4 features
  Example: 6 data points with 4 features each (typical tabular data)

### Flatten back to 1-D ###
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
Shape: (24,)

ML Scenario Interpretation:
  - Single 1-D array: Can be used as

In [6]:
import numpy as np

# Create a 6×6 matrix of random floats in [0, 1)
matrix = np.random.rand(6, 6)
print("Original 6×6 matrix:")
print(matrix)
print()

# Extract every other row (rows 0, 2, 4)
every_other_row = matrix[::2, :]
print("Every other row (rows 0, 2, 4):")
print(every_other_row)
print()

# Extract the diagonal using np.diag
diagonal = np.diag(matrix)
print("Diagonal of original matrix:")
print(diagonal)
print()

# Apply threshold: replace values > 0.7 with 1, everything else with 0
binary_matrix = np.where(matrix > 0.7, 1, 0)
print("Binary matrix (threshold at 0.7):")
print(binary_matrix)
print()

# Alternative: using conditional assignment
# binary_matrix = matrix.copy()
# binary_matrix[binary_matrix > 0.7] = 1
# binary_matrix[binary_matrix <= 0.7] = 0

Original 6×6 matrix:
[[3.18095038e-01 8.90099041e-01 9.92964351e-01 2.74443934e-01
  4.01358180e-01 6.23783696e-01]
 [5.04527974e-02 7.29734854e-01 6.90587711e-01 8.33579717e-01
  4.67102531e-01 4.40123279e-01]
 [6.23914562e-01 5.29254540e-02 1.93446070e-01 1.76120860e-01
  8.58997337e-01 1.85211157e-01]
 [9.62393741e-02 2.76487307e-01 6.19361079e-01 3.53230298e-01
  6.81213050e-01 7.53638043e-01]
 [5.04373306e-01 7.12742828e-01 4.97379302e-01 7.48639925e-04
  9.01547830e-01 6.32174412e-01]
 [6.94119284e-01 9.53020704e-01 4.77334594e-01 2.33700725e-01
  3.95570946e-01 6.31989694e-01]]

Every other row (rows 0, 2, 4):
[[3.18095038e-01 8.90099041e-01 9.92964351e-01 2.74443934e-01
  4.01358180e-01 6.23783696e-01]
 [6.23914562e-01 5.29254540e-02 1.93446070e-01 1.76120860e-01
  8.58997337e-01 1.85211157e-01]
 [5.04373306e-01 7.12742828e-01 4.97379302e-01 7.48639925e-04
  9.01547830e-01 6.32174412e-01]]

Diagonal of original matrix:
[0.31809504 0.72973485 0.19344607 0.3532303  0.90154783 0.6

In [7]:
import numpy as np

# Set random seed for reproducibility
np.random.seed(42)

# Create two (4, 3) matrices of random values
matrix_1 = np.random.rand(4, 3)
matrix_2 = np.random.rand(4, 3)

print("Original Matrix 1:")
print(matrix_1)
print("\nOriginal Matrix 2:")
print(matrix_2)
print()

# Stack them vertically with np.vstack
vstack_result = np.vstack((matrix_1, matrix_2))
print("Vertically stacked result (shape: (8, 3)):")
print(vstack_result)
print(f"Shape: {vstack_result.shape}")
print()

# Stack them horizontally with np.hstack
hstack_result = np.hstack((matrix_1, matrix_2))
print("Horizontally stacked result (shape: (4, 6)):")
print(hstack_result)
print(f"Shape: {hstack_result.shape}")
print()

# Split the vertical result back into two equal arrays using np.vsplit
split_result = np.vsplit(vstack_result, 2)
split_matrix_1 = split_result[0]
split_matrix_2 = split_result[1]

print("First matrix from vertical split:")
print(split_matrix_1)
print("\nSecond matrix from vertical split:")
print(split_matrix_2)
print()

# Assert that the split arrays match the originals
print("Performing assertions...")
try:
    assert np.allclose(split_matrix_1, matrix_1), "First split matrix doesn't match original matrix 1"
    print("✓ First split matrix matches original matrix 1")
    
    assert np.allclose(split_matrix_2, matrix_2), "Second split matrix doesn't match original matrix 2"
    print("✓ Second split matrix matches original matrix 2")
    
    print("\n✓ All assertions passed! Split matrices match the originals.")
except AssertionError as e:
    print(f"✗ Assertion failed: {e}")

Original Matrix 1:
[[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]
 [0.70807258 0.02058449 0.96990985]]

Original Matrix 2:
[[0.83244264 0.21233911 0.18182497]
 [0.18340451 0.30424224 0.52475643]
 [0.43194502 0.29122914 0.61185289]
 [0.13949386 0.29214465 0.36636184]]

Vertically stacked result (shape: (8, 3)):
[[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]
 [0.70807258 0.02058449 0.96990985]
 [0.83244264 0.21233911 0.18182497]
 [0.18340451 0.30424224 0.52475643]
 [0.43194502 0.29122914 0.61185289]
 [0.13949386 0.29214465 0.36636184]]
Shape: (8, 3)

Horizontally stacked result (shape: (4, 6)):
[[0.37454012 0.95071431 0.73199394 0.83244264 0.21233911 0.18182497]
 [0.59865848 0.15601864 0.15599452 0.18340451 0.30424224 0.52475643]
 [0.05808361 0.86617615 0.60111501 0.43194502 0.29122914 0.61185289]
 [0.70807258 0.02058449 0.96990985 0.13949386 0.29214465 0.36636184]]
S

In [8]:
np.random.seed(42)

# Create two (4, 3) matrices
m1 = np.random.rand(4, 3)
m2 = np.random.rand(4, 3)

# Stack vertically and horizontally
vstack = np.vstack((m1, m2))
hstack = np.hstack((m1, m2))

print(f"vstack shape: {vstack.shape}")
print(f"hstack shape: {hstack.shape}")

# Split and assert
s1, s2 = np.vsplit(vstack, 2)
assert np.allclose(s1, m1) and np.allclose(s2, m2)
print("✓ Split matrices match originals")

vstack shape: (8, 3)
hstack shape: (4, 6)
✓ Split matrices match originals


In [9]:
import numpy as np

np.random.seed(42)

m1 = np.random.rand(4, 3)
m2 = np.random.rand(4, 3)

vstack = np.vstack((m1, m2))
hstack = np.hstack((m1, m2))

s1, s2 = np.vsplit(vstack, 2)

print(f"vstack: {vstack.shape} | hstack: {hstack.shape}")
print(f"Match: {np.allclose(s1, m1) and np.allclose(s2, m2)}")

vstack: (8, 3) | hstack: (4, 6)
Match: True


In [10]:
import numpy as np

# Create (4, 1) column vector and (1, 5) row vector
col = np.array([[1], [2], [3], [4]])
row = np.array([[1, 2, 3, 4, 5]])

result1 = col + row
print(f"(4,1) + (1,5) = {result1.shape}")

# Add (3,) array to (4, 3) matrix
arr = np.array([10, 20, 30])
matrix = np.ones((4, 3))
result2 = matrix + arr
print(f"(4,3) + (3,) = {result2.shape}")

# Broadcasting explanation:
# NumPy broadcasts smaller arrays to match larger ones along dimensions
# (4,1) + (1,5) → (4,5): column broadcasts across columns, row across rows
# (4,3) + (3,) → (4,3): (3,) is treated as (1,3) and broadcasts down to 4 rows

(4,1) + (1,5) = (4, 5)
(4,3) + (3,) = (4, 3)


In [11]:
import numpy as np
import time

# Generate 1,000,000 random floats
data = np.random.rand(1_000_000)

# Approach (a): Element-by-element with Python for-loop
start = time.time()
result_loop = [x ** 0.5 for x in data]
time_loop = time.time() - start

# Approach (b): NumPy sqrt
start = time.time()
result_numpy = np.sqrt(data)
time_numpy = time.time() - start

# Calculate speedup
speedup = time_loop / time_numpy

print(f"Python for-loop:     {time_loop:.4f} seconds")
print(f"NumPy np.sqrt():     {time_numpy:.4f} seconds")
print(f"Speedup factor:      {speedup:.1f}x faster")
print(f"\nNumPy is {speedup:.0f} times faster than Python loops!")

Python for-loop:     0.9543 seconds
NumPy np.sqrt():     0.0224 seconds
Speedup factor:      42.5x faster

NumPy is 43 times faster than Python loops!


In [12]:
import numpy as np

np.random.seed(42)

# Create (100, 5) matrix: 100 samples, 5 features
data = np.random.randn(100, 5) * 10 + 50  # Random data with mean ~50, std ~10

print("Original data (first 5 rows):")
print(data[:5])
print(f"\nOriginal means: {data.mean(axis=0)}")
print(f"Original stds:  {data.std(axis=0)}")

# Normalize: (X - mean) / std
mean = data.mean(axis=0)
std = data.std(axis=0)
normalized = (data - mean) / std

print("\n" + "="*50)
print("Normalized data (first 5 rows):")
print(normalized[:5])
print(f"\nNormalized means: {normalized.mean(axis=0)}")
print(f"Normalized stds:  {normalized.std(axis=0)}")

# Verify
assert np.allclose(normalized.mean(axis=0), 0, atol=1e-10)
assert np.allclose(normalized.std(axis=0), 1, atol=1e-10)
print("\n✓ Verification passed! Means ≈ 0 and stds ≈ 1")

Original data (first 5 rows):
[[54.96714153 48.61735699 56.47688538 65.23029856 47.65846625]
 [47.65863043 65.79212816 57.67434729 45.30525614 55.42560044]
 [45.36582307 45.34270246 52.41962272 30.86719755 32.75082167]
 [44.37712471 39.8716888  53.14247333 40.91975924 35.87696299]
 [64.65648769 47.742237   50.67528205 35.75251814 44.55617275]]

Original means: [49.55252814 50.76954231 49.06126489 51.28058469 49.67797969]
Original stds:  [ 8.95839205  9.79177204  9.79011416  9.54745759 10.67428569]

Normalized data (first 5 rows):
[[ 0.604418   -0.21979528  0.75746006  1.461092   -0.18919425]
 [-0.21141045  1.53420502  0.87977344 -0.62585547  0.53845484]
 [-0.46735006 -0.55422449  0.34303561 -2.13809665 -1.58578836]
 [-0.57771567 -1.1129603   0.41687036 -1.08519209 -1.2929218 ]
 [ 1.68601234 -0.30916828  0.16486193 -1.62640854 -0.47982667]]

Normalized means: [-3.01980663e-16  3.59712260e-16  1.34114941e-15  2.42028619e-16
 -1.48103751e-15]
Normalized stds:  [1. 1. 1. 1. 1.]

✓ Verifica

In [13]:
import numpy as np

np.random.seed(42)

# Create (100, 5) matrix
data = np.random.randn(100, 5) * 10 + 50

# Normalize: (X - mean) / std
normalized = (data - data.mean(axis=0)) / data.std(axis=0)

print(f"Normalized means: {normalized.mean(axis=0)}")
print(f"Normalized stds:  {normalized.std(axis=0)}")

assert np.allclose(normalized.mean(axis=0), 0) and np.allclose(normalized.std(axis=0), 1)
print("✓ Verification passed!")

Normalized means: [-3.01980663e-16  3.59712260e-16  1.34114941e-15  2.42028619e-16
 -1.48103751e-15]
Normalized stds:  [1. 1. 1. 1. 1.]
✓ Verification passed!


In [14]:
import numpy as np

np.random.seed(42)

# Create (100, 5) matrix
data = np.random.randn(100, 5) * 10 + 50

# Min-max scaling: (X - min) / (max - min)
min_val = data.min(axis=0)
max_val = data.max(axis=0)
scaled = (data - min_val) / (max_val - min_val)

print(f"Scaled min: {scaled.min(axis=0)}")
print(f"Scaled max: {scaled.max(axis=0)}")

# Test point outside training range
test_point = np.array([[100, 100, 100, 100, 100]])
test_scaled = (test_point - min_val) / (max_val - min_val)

print(f"\nTest point (outside range): {test_point[0]}")
print(f"Scaled test point: {test_scaled[0]}")

# Comment: A test point outside the training range will NOT stay in [0, 1].
# Values > max scale to > 1, values < min scale to < 0.
# This is a limitation of min-max scaling: it doesn't generalize to unseen ranges.
# Standardization (z-score) is more robust for out-of-range test points.

Scaled min: [0. 0. 0. 0. 0.]
Scaled max: [1. 1. 1. 1. 1.]

Test point (outside range): [100 100 100 100 100]
Scaled test point: [1.62936514 1.74348961 1.53656844 1.38482717 1.1772534 ]


In [15]:
import numpy as np

np.random.seed(42)

# Create weight matrix W (4, 3) and input X (3, 10)
W = np.random.randn(4, 3)
X = np.random.randn(3, 10)

# Forward pass: Z = W @ X
Z = W @ X
print(f"Z shape: {Z.shape}")
assert Z.shape == (4, 10), "Output shape mismatch!"

# Add bias vector (4, 1) using broadcasting
b = np.random.randn(4, 1)
output = Z + b

print(f"Output shape (with bias): {output.shape}")
print(f"\nFirst 3 samples:\n{output[:, :3]}")
print("✓ Linear layer complete!")

Z shape: (4, 10)
Output shape (with bias): (4, 10)

First 3 samples:
[[-0.01354094 -1.55407709 -0.36441777]
 [ 0.05476031 -2.63382782 -2.99332416]
 [-1.03825198 -5.09683172 -5.00647631]
 [-0.61357285 -0.60505265 -1.78652276]]
✓ Linear layer complete!


In [16]:
# exercice 1
import numpy as np

# (1) 1-D array of 20 evenly spaced values between 0 and 1
arr1 = np.linspace(0, 1, 20)

# (2) 5×5 identity matrix
arr2 = np.eye(5)

# (3) 3×4 matrix of random integers between 1 and 100
arr3 = np.random.randint(1, 101, (3, 4))

print(f"Array 1 - Shape: {arr1.shape}, dtype: {arr1.dtype}")
print(f"Array 2 - Shape: {arr2.shape}, dtype: {arr2.dtype}")
print(f"Array 3 - Shape: {arr3.shape}, dtype: {arr3.dtype}")

Array 1 - Shape: (20,), dtype: float64
Array 2 - Shape: (5, 5), dtype: float64
Array 3 - Shape: (3, 4), dtype: int32


In [17]:
#exercice2
import numpy as np

# Create 1-D array of integers from 1 to 24
arr = np.arange(1, 25)
print(f"Original shape: {arr.shape}")

# Reshape to (2, 3, 4): 2 batches, 3 timesteps, 4 features
arr = arr.reshape(2, 3, 4)
print(f"After reshape(2, 3, 4): {arr.shape}  # 2 batches, 3 timesteps, 4 features")

# Reshape to (6, 4): 6 samples, 4 features
arr = arr.reshape(6, 4)
print(f"After reshape(6, 4): {arr.shape}  # 6 samples, 4 features each")

# Flatten back to 1-D
arr = arr.flatten()
print(f"After flatten(): {arr.shape}")
print(f"Values: {arr}")

Original shape: (24,)
After reshape(2, 3, 4): (2, 3, 4)  # 2 batches, 3 timesteps, 4 features
After reshape(6, 4): (6, 4)  # 6 samples, 4 features each
After flatten(): (24,)
Values: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
